dist: xenial

sudo: required

language: python

services:
    - docker

python: '3.7'

before_install:
    - git clone --single-branch --branch 2.0.0-dev https://github.com/PremierLangage/sandbox.git ../sandbox
    - cd ../sandbox
    - ./bin/install.sh
    - python3 manage.py runserver 7000 &
    - cd -

install:
    - pip install -U wheel setuptools
    - pip install tox-travis
    - pip install codecov

script: tox

after_success: codecov

deploy:
    provider: pypi
    skip_existing: true
    user: qcoumes
    password:
        secure: oo1yGdwHDqbydufYZkLTySM8F0fhotNj6tNXkoA46K2zPww/kn0/NKWt8LdWnDdy7mjKYhFSZSn6a5MMLgVPsLp+lTB3hn22Ryf9OSIfg7ryU9k71IR04nmPGvl0ANBhkU/dauUrpgh/f9xqdY3Uq7In0//ATpdhwEKFYyk8rjx7JnZMxdZwF+GyqMXAZ1FX8LP0IeDImJG7Dbm6vZ5NPTFRcm8xpRMw8h5MY7Y9rOijQsS2c0m+1fYnpfFw6L5nOHQADwztdAbDV1V6irOAZnmGH22h5H7jXCC9Q9gsGb5/Sn2v51gwYSvcc6NM1L/twRtsorn+qY8HwdNu3dIkpKZveFZet6wT9tttSRtcNAgDnPcU89vTBrnqfjVpQJIn8KSVAkiodSkEJSZ1VdfZEw2NXmEnbRKMi+A7300nl4YAEQQz9W+YgsGLkQmOgBJMM+y2ws4y9aXt1IBZgS91jN/dx9B8DILAJ02Hmtc7XH+aIH1rD6+mvPBR7MuhCZdeEkqvJ3uBSi9ccoZhBsfzYs99X3z72C3ov4CrGidzH+keEUEBXidMK4lWQUXQ5idURFphzJw0TEYV3duU6NPjz431kZUu6Fg+Lyvsi/I78GbC2yDEW+b+/e1XdujhdkEUobJWhsKy6Jx8pnV42+sZ4yGK2CbBWSVlQrLOGU+JlgY=
    on:
        condition: "$TRAVIS_EVENT_TYPE != cron"
